### ISSUE TITLE
Why to use de clippboard?

### ISSUE THREAD

**Issue by Brnd08** [tonikelope/coronapoker#4]
I just would like to know why you need to get the System Clipboard

**Comment by tonikelope** [comment]
Hi. It is mainly used to detect links from Google DUO in order to share them more easily via in-game chat. The clipboard link detection feature is only active while the VIDEOCHAT window is open (inside the chat).

The clipboard is also used to copy the server connection data and game password to the clipboard for easier sharing with friends.

Regards.
