### ISSUE TITLE
How to add new players when pause the game?

### ISSUE THREAD

**Issue by whatagoodboy** [tonikelope/coronapoker#5]
Hi, the Features "It is possible to pause the game at any time and add new players."，but when the host pause the game , the new player got the message "u r late" and  can't join the game .please tell us how to add new players when pause the game? Thanks!

**Comment by tonikelope** [comment]
Hi. Adding new players to a started game is possible, but you have to stop the game. Here are the recommended steps to add a player (or players) to a started game:

1) The server activates the last hand (so that the game is stopped when the hand in play ends).

2) Once the game ends the server creates a new game by CHECKING the RESUME GAME checkbox.

3) Old and new players can connect to the game.

4) Start playing.

Regards.
